# config/convnet_mnist.yaml

# ================================================================
# DEFAULT CONFIGURATIONS
# ================================================================
default:
  device: cpu
  save_layer_images: true
  collect_metrics: true

# ================================================================
# LOGGING CONFIGURATIONS
# ================================================================
logging:
  log_level: DEBUG
  log_file: logs/convnet_mnist.log

# ================================================================
# MODEL CONFIGURATIONS
# ================================================================
model:
  model_name: convnet
  version: null
  pretrained: false
  weight_path: data/MNIST/weights/mnist.pth
  input_size: [1, 28, 28]
  split_layer: 1
  save_layers: [1, 2]
  hidden_size: 64
  num_classes: 10
  mode: eval
  depth: 2
  flush_buffer_size: 100
  warmup_iterations: 10
  log_file: logs/convnet_mnist.log

# ================================================================
# DATASET CONFIGURATIONS
# ================================================================
dataset:
  name: "mnist"
  root: "data/MNIST"
  train: true
  transform: null
  max_samples: 100  # Very small sample for quick testing

# ================================================================
# DATALOADER CONFIGURATIONS
# ================================================================
dataloader:
  batch_size: 1
  shuffle: false
  num_workers: 0
  collate_fn: null

# ================================================================
# COMPRESSION CONFIGURATIONS
# ================================================================
compression:
  clevel: 3
  filter: SHUFFLE
  codec: ZSTD

# ================================================================
# ENCRYPTION CONFIGURATIONS
# ================================================================
encryption:
  enabled: true                   # Set to true to enable encryption
  mode: "full"             # "transmission" (default) or "full" (homomorphic)
  password: null                   # Optional password for encryption
  key_file: null                   # Optional path to encryption key file
  degree: 8192                     # Polynomial modulus degree for encryption
  scale: 26                        # Bit scale for encoding precision 